[
        "payment_slip <- list()\n",
        "\n",
        "# create the workers data and store it in a list of lists\n",
        "for(i in 1:400) {\n",
        "    worker_id <- i\n",
        "    worker_name <- paste(\"worker_\", worker_id)\n",
        "    gender <- sample(c(\"Male\", \"Female\"), 1) # Sample one gender\n",
        "    salary <- runif(1, 5000, 30000) # Sample one salary\n",
        "\n",
        "    # create a list containing worker's data\n",
        "    worker_data <- list(\n",
        "        \"name\" = worker_name,\n",
        "        \"gender\" = gender,\n",
        "        \"salary\" = salary\n",
        "    )\n",
        "    # append the worker's data to the payment_slip list\n",
        "    payment_slip[[i]] <- worker_data\n",
        "}\n",
        "\n",
        "for (worker in payment_slip) {\n",
        "    employment_level <- tryCatch({\n",
        "        if (worker$salary > 10000 && worker$salary < 20000) {\n",
        "            \"A1\"\n",
        "        } else if (worker$salary > 7500 && worker$salary < 30000 && worker$gender == \"Female\") {\n",
        "            \"A5-F\"\n",
        "        } else {\n",
        "            stop(\"NA\")  # trigger an exception\n",
        "        }\n",
        "    }, error = function(e) {\n",
        "        paste(e$message)\n",
        "    })\n",
        "\n",
        "    cat(strrep(\"=\", 40), \"\\n\")\n",
        "    cat(\"Highridge Construction Company\\n\")\n",
        "    cat(strrep(\"-\", 40), \"\\n\")\n",
        "    cat(\"employee_name:\", worker$name, \"\\n\")\n",
        "    cat(\"gender:\", worker$gender, \"\\n\")\n",
        "    cat(\"salary: $\", worker$salary, \"\\n\")\n",
        "    cat(\"employment_level:\", employment_level, \"\\n\")\n",
        "    cat(\"\\n\")\n",
        "}"
      ]
    }
  ]
}